### PR TITLE
TOOLS-3110 Fix CI issues with 6.0+

### PR DESCRIPTION
**Pull request by autarch**
The 6.0 release no longer includes the shell, but we need the shell to run tests.

Now when we are testing against 6.0+, we download the most recent 5.x release for that platform and use the shell from that release.

### CODE REVIEW

**Comment by autarch** [comment]
CI is passing on a variety of tasks, including 6.0 and latest on all platforms:

* https://spruce.mongodb.com/version/62a26a5c1e2d17797cd8b452/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
* https://spruce.mongodb.com/version/62a2694da4cf472433c3fe74/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

**Review by tfogo — CHANGES_REQUESTED** [review]
This is great, the new python file looks much tidier.

It looks like it's failing on RHEL6 due to the python version, though.

Also, do have a patch where the qa-tests and legacy-jstests run?

**Comment by autarch** [comment]
Things to try to fix the issues with the resmoke code ...

First, get rid of my incremental fixes by reverting to 4132e02.

* Try running the `2to3` program
* Try copying in a newer version of resmoke from mongosync.

**Comment by tfogo** [comment]
Closing this in favor of #447

**Pull request closed without merging**
