### PR TITLE
TOOLS-2833 Correctly parse partialFilterExpression in index builds during oplogReplay

### PR DESCRIPTION
**Pull request by tfogo**
I added a second index build that has a partialFilterExpression to `testdata/commit_indexes_build/oplog.bson` and `testdata/create_indexes/oplog.bson` so that we have test coverage for this.

### CODE REVIEW

**Comment by rychipman** [comment]
@huan-Mongo I'm assuming it was an accident that you closed this PR?

**Comment by huan-Mongo** [comment]
@rychipman Ah, yes! Sorry, I guess I closed the wrong ticket. Thanks for catching this.

**Comment by huan-Mongo** [comment]
@rychipman Ah, yes! I guess I closed the wrong ticket. Thanks for catching this!

**Review by huan-Mongo — APPROVED** [review]
LGTM!

**Pull request merged**
