### PR TITLE
TOOLS-3052 Add ARM builds for Amazon Linux 2023

### PR DESCRIPTION
**Pull request by FGasper**

### CODE REVIEW

**Review by huan-Mongo — APPROVED** [review]
LGTM!

**Review by jtcovan — APPROVED** [review]
LGTM

**Comment by FGasper** [comment]
evergreen merge

**Comment by tfogo** [comment]
Do you need to update the repo config too? https://github.com/mongodb/mongo-tools/blob/master/etc/repo-config.yml 

See: https://github.com/mongodb/mongo-tools/blob/master/PLATFORMSUPPORT.md

**Pull request merged**
