### PR TITLE
TOOLS-1997 mongostat needs to handle large counters encoded as floats

### PR DESCRIPTION
**Pull request by mzraly**
This is a minor change to display differences and rates computed from counter values larger than 1<<30, which get stored as doubles instead of signed integers.

### CODE REVIEW

**Comment by xdg** [comment]
Could you please add a check for the `float64` case to ensure that the pre-conversion value fits within `math.MinInt64` and `math.MaxInt64`?  If, for some reason, the float doesn't fit, there should be an error rather than a cast.

**Comment by mzraly** [comment]
Certainly, will try to get to that this evening.

**Comment by xdg** [comment]
Thanks.  Just FYI, I'm not going to get a chance to merge this for a while as I'm going away to a conference and then have some urgent ticket to address before the end of the month.

**Comment by tfogo** [comment]
I'm going through stale PRs to try to clean them up. Sorry this PR has been stale for such a long time.

Unfortunately this fix is not a priority for the Tools team at the moment. I appreciate the work you put into this PR, but I think we're going to have to close it since we don't have any current plans to fix this.

**Pull request closed without merging**
