### PR TITLE
TOOLS-936: Add option to allow mongorestore to build indexes in the foreground

### PR DESCRIPTION
**Pull request by sindbach**
Default to always build background indexes. Specify option `--allowForegroundIndexBuild` to build indexes according to the `*.metadata.json` file.

### CODE REVIEW

**Comment by jaraco** [comment]
The title of this PR doesn't match the description. Suggest s/force/allow/.

**Comment by gabrielrussell** [comment]
Do you need this backported to 3.4, or just in 3.6? Because this includes a change of default behavior, I wouldn't want to backport it to 3.4. If you need background index builds in 3.4, the default should still be to do foreground builds.

**Comment by jaraco** [comment]
As long as 3.6 tools can work with older but recent releases of mongod, I see no issue with only including this with 3.6.

**Comment by sindbach** [comment]
@gabrielrussell Just in 3.6 would be great. Thanks.

**Comment by H-Max** [comment]
I think it would be great to add an option to build indexes in the background prior to 3.6, and make it defaults starting in 3.6.

(Just my 2 cents)

**Pull request closed without merging**
