### PR TITLE
Fix for TOOLS-2744

### PR DESCRIPTION
**Pull request by rakshitCrazyB**
Fix for TOOLS-2744

### CODE REVIEW

**Comment by edobranov** [comment]
Hi @rakshitCrazyB, we apologize for the delayed response. Thank you for your patience and for submitting this PR.

It looks good to us, so we'd be happy to merge your change. Before we do that though, could we ask you to sign our [Contributor Agreement](https://www.mongodb.com/legal/contributor-agreement) (full guidelines [here](https://github.com/mongodb/mongo/wiki) if you're curious)? Feel free to comment back to let us know when you've done that.

Thanks again!

**Comment by rakshitCrazyB** [comment]
> Hi @rakshitCrazyB, we apologize for the delayed response. Thank you for your patience and for submitting this PR.
> 
> It looks good to us, so we'd be happy to merge your change. Before we do that though, could we ask you to sign our [Contributor Agreement](https://www.mongodb.com/legal/contributor-agreement) (full guidelines [here](https://github.com/mongodb/mongo/wiki) if you're curious)? Feel free to comment back to let us know when you've done that.
> 
> Thanks again!
@edobranov 
I have signed the contributor agreement.

Thanks

**Comment by rakshitCrazyB** [comment]
> Hi @rakshitCrazyB, we apologize for the delayed response. Thank you for your patience and for submitting this PR.
> 
> It looks good to us, so we'd be happy to merge your change. Before we do that though, could we ask you to sign our [Contributor Agreement](https://www.mongodb.com/legal/contributor-agreement) (full guidelines [here](https://github.com/mongodb/mongo/wiki) if you're curious)? Feel free to comment back to let us know when you've done that.
> 
> Thanks again!

@edobranov 
I have signed the Contributor Agreement .

Thanks

**Review by edobranov — APPROVED** [review]
Perfect! You should be able to merge the PR now. I can also merge it for you if you can't.

Thanks again :)

**Comment by rakshitCrazyB** [comment]
> Perfect! You should be able to merge the PR now. I can also merge it for you if you can't.
> 
> Thanks again :)

@edobranov
I don't have write access to the repo. Kindly merge.

**Comment by edobranov** [comment]
Cool, I just merged for you. I'll close out the ticket you filed too (https://jira.mongodb.org/browse/TOOLS-2744). Let us know if anything else comes up!

**Pull request merged**
