### PR TITLE
TOOLS-2707: Build mongo-tools with go 1.15

### PR DESCRIPTION
**Pull request by huan-Mongo**

### CODE REVIEW

**Review by tfogo — CHANGES_REQUESTED** [review]
Looks like SUSE 15 is failing in the test because it can't find the 1.15 binaries. Has the build team fixed that yet? I restarted the test to check.

Also, can you include an update to the supported version in the readme?

**Comment by tfogo** [comment]
Yeah SUSE 15 is still failing.

**Comment by huan-Mongo** [comment]
Sure, I will add the supported version and added SUSE 15 build ticket to the dependency. I will first close this PR and reopen after the build ticket is finished.

**Comment by huan-Mongo** [comment]
@tfogo I fixed SUSE15 and now all the tests passed except for those always been failing. Please take another look, thx!

**Review by tfogo — APPROVED** [review]
Nice! LGTM!

**Pull request merged**
