### PR TITLE
TOOLS-1696 Fix possible nil dereference in SessionProvider.Close.

### PR DESCRIPTION
**Pull request by ShaneHarvey**
Jira: https://jira.mongodb.org/browse/TOOLS-1696

### CODE REVIEW

**Comment by billybanfield** [comment]
This looks fine, just needs a tools ticket and to be prefixed with TOOLS-1234 MESSAGE

**Comment by ShaneHarvey** [comment]
Done.

**Comment by billybanfield** [comment]
lgtm, will merge.

**Comment by billybanfield** [comment]
master @ dc68a32d45121428117234c5d8f04d9b2f50bdee

**Pull request closed without merging**
