### PR TITLE
TOOLS-2597: swallows errors from URI parsing

### PR DESCRIPTION
**Pull request by huan-Mongo**
This PR just pulls in the new MTC changes

### CODE REVIEW

**Comment by tfogo** [comment]
Looks like this is revendoring the version before the error message fix?

**Comment by tfogo** [comment]
We should merge https://github.com/mongodb/mongo-tools-common/pull/42 first?

**Comment by huan-Mongo** [comment]
Ah, you are right. I forgot that one! Thx, will merge that first.

**Comment by huan-Mongo** [comment]
@tfogo I just revendored the new version, please take a look. Thx!

**Comment by huan-Mongo** [comment]
Since Hari revendored MTC to 3.0.13 in https://github.com/mongodb/mongo-tools/pull/261, This PR is not needed. Closing.

**Pull request closed without merging**
